#!/bin/bash

targetApp="/Applications/Google Chrome.app"

targetPID=$(ps aux | grep -v grep | grep "${targetApp}/Contents/MacOS/Google Chrome" | awk '{print $2}')

if [ -z "$targetPID" ]
   then
      echo "${targetApp} not running"
   else
      echo "${targetApp} running, killing process ID ${targetPID}"
      kill -9 "$targetPID"
fi

if [ -d "${targetApp}" ]
  then
    echo "${targetApp} found on disk"
    rm -R "${targetApp}"
    echo "${targetApp} removed"
  else
    echo "${targetApp} not found on disk"
fi

exit 0
